apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashnboard
  labels:
    app: dashnboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashnboard
  template:
    metadata:
      labels:
        app: dashnboard
    spec:
      containers:
        - name: dashnboard
          image: username/dashnboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
